<script setup>
// This starter template is using Vue 3 <script setup> SFCs
// Check out https://vuejs.org/api/sfc-script-setup.html#script-setup
import HeaderNavbar from '@/components/views/HeaderNavbar.vue'
import FooterNavbar from '@/components/views/FooterNavbar.vue'
import NavbarProfile from '@/components/views/NavbarProfile.vue'
</script>

<template>
    <header>
        <HeaderNavbar v-if="!$route.meta.requireAuth" />
        <NavbarProfile v-else />
    </header>

    <main>
        <router-view />
    </main>

    <footer>
        <FooterNavbar />
    </footer>
</template>

<style lang="scss">
// Заменить перед рефакторингом
// @import '//dev.iconly.io/public/d0fEAcR18FIx/iconly.css';
/*!
 *  fadi icon font. Generated by Iconly: https://iconly.io/
 */

@font-face {
    font-display: auto;
    font-family: 'fadi';
    font-style: normal;
    font-weight: 400;
    src: url('@/assets/fonts/icons/ui/iconly.eot?1668274299326');
    src: url('@/assets/fonts/icons/ui/iconly.eot?#iefix') format('embedded-opentype'), url('@/assets/fonts/icons/ui/iconly.woff2?1668274299326') format('woff2'),
        url('@/assets/fonts/icons/ui/iconly.woff?1668274299326') format('woff'), url('@/assets/fonts/icons/ui/iconly.ttf?1668274299326') format('truetype'),
        url('@/assets/fonts/icons/ui/iconly.svg?1668274299326#fadi') format('svg');
}

[class='icon'],
[class^='icon-'],
[class*=' icon-'] {
    display: inline-block;
    font-family: 'fadi' !important;
    font-weight: 400;
    font-style: normal;
    font-variant: normal;
    text-rendering: auto;
    line-height: 1;
    -moz-osx-font-smoothing: grayscale;
    -webkit-font-smoothing: antialiased;
}

.icon-user:before {
    content: '\e000';
}

.icon-telegram:before {
    content: '\e001';
}

.icon-basket:before {
    content: '\e002';
}

.icon-search:before {
    content: '\e003';
}

.icon-dots:before {
    content: '\e004';
}

.icon-paperclip:before {
    content: '\e005';
}

.icon-menu:before {
    content: '\e006';
}

.icon-mastercard:before {
    content: '\e007';
}

.icon-chevron:before {
    content: '\e008';
}

.icon-bell:before {
    content: '\e009';
}

.icon-eye:before {
    content: '\e00a';
}

.icon-heart:before {
    content: '\e00b';
}

.icon-chat:before {
    content: '\e00c';
}

.icon-arrow-top-right:before {
    content: '\e00d';
}

.icon-visa:before {
    content: '\e00e';
}

@font-face {
    font-family: 'Roboto';
    src: url('@/assets/fonts/roboto/Roboto-Regular.woff2?#iefix') format('woff2'), url('@/assets/fonts/roboto/Roboto-Regular.woff') format('woff'),
        url('@/assets/fonts/roboto/Roboto-Regular.ttf') format('truetype');
    font-weight: 400;
    font-style: normal;
    font-display: auto;
    unicode-range: U+000-5FF;
}

@font-face {
    font-family: 'Roboto';
    src: url('@/assets/fonts/roboto/Roboto-Bold.woff2?#iefix') format('woff2'), url('@/assets/fonts/roboto/Roboto-Bold.woff') format('woff'),
        url('@/assets/fonts/roboto/Roboto-Bold.ttf') format('truetype');
    font-weight: 700;
    font-style: normal;
    font-display: auto;
    unicode-range: U+000-5FF;
}

:root {
    --scheme-v1: #151515;
    --scheme-v2: #d69828;
    --scheme-v3: #cccccc;
    --scheme-v4: #ffffff;
    --scheme-v5: #29aaeb;

    // project font-family
    --scheme-font: 'Roboto', 'Helvetica', Arial, sans-serif;
    --scheme-h: 82px;
    --scheme-m: 64px;
    --scheme-xm: 45px;
    --scheme-s: 16px;

    // project default template width
    --scheme-max-width: 1480px; // desktop
    --scheme-min-width: 320px; // 5 SE

    // project default template height
    --scheme-min-height: 568px; // 5 SE

    // project default template gap
    --scheme-gap: 40px;

    // project ex. header & footer height
    --scheme-offset: 100px;

    font-synthesis: none;
    text-rendering: optimizeLegibility;

    -webkit-font-smoothing: antialiased;
    -moz-osx-font-smoothing: grayscale;
    -webkit-text-size-adjust: 100%;
}

@media all and (max-width: 60em) {
    :root {
        --scheme-m: 42px;
        --scheme-xm: 32px;
    }
}

* {
    box-sizing: border-box;
    margin: 0;
}

html,
body {
    height: 100%;
}

body {
    color: var(--scheme-v1);

    font: 400 var(--scheme-s) / 1.64 var(--scheme-font);

    min-width: 360px;
    position: relative;
}

header,
section {
    margin: auto;
    max-width: var(--scheme-max-width);
    padding: var(--scheme-gap);
}

footer {
    background-color: #fafafa;
}

h1,
h2,
h3,
h4,
h5 {
    font-weight: 400;
}

h1 {
    font: 700 var(--scheme-h) / 1 var(--scheme-font);
}

h2 {
    font: 400 var(--scheme-h) / 1.42 var(--scheme-font);
    margin: 0 0 40px;
}

h3 {
    font: 400 var(--scheme-m) / 1.42 var(--scheme-font);
}

h4 {
    font: 400 var(--scheme-xm) / 1.42 var(--scheme-font);
}

h5 {
    font: 400 20px / 1.42 var(--scheme-font);
}

a {
    color: inherit;
    text-decoration: none;
}

b {
    font-weight: 400;
}

strong {
    font: inherit;
}

ul {
    padding: 0;

    li {
        list-style: none;
    }
}

svg {
    vertical-align: middle;
}

legend {
    padding: 0;
    display: table;
}

fieldset {
    border: 0;
    padding: 0.01em 0 0 0;
    margin: 0;
    min-width: 0;
}

body:not(:-moz-handler-blocked) fieldset {
    display: table-cell;
}

input,
button {
    background: none;
    border: none;
    box-shadow: none;

    font: 100 var(--scheme-s) / 3 var(--scheme-font);

    margin: 0;
    outline: none;
    padding: 0;
}

button {
    border-radius: 50px;
    cursor: pointer;
    text-transform: uppercase;
    white-space: nowrap;
}
</style>
